# Generated by Django 2.2.6 on 2020-04-17 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_big_case', '0002_auto_20200417_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 9, 51, 0, 364080, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
