# Generated by Django 2.2.6 on 2020-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_big_case', '0003_auto_20200417_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('file', models.FileField(blank=True, null=True, upload_to='up_file', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '上传文件和图片',
                'verbose_name_plural': '上传文件和图片',
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
