# Generated by Django 2.2.6 on 2020-04-20 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_big_case', '0004_auto_20200420_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 29, 49, 232146, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
